### ISSUE TITLE
Issues setting up

### ISSUE THREAD

**Issue by marktillo** [MadmanMonty/Home_Assistant_SkyQ_MediaPlayer#3]
How, where do I set up the sky<Room>.yaml
Tried following the instructions but I’m coming up blank, quite a noobie to HA

**Comment by MadmanMonty** [comment]
You don't need to create a sky.yaml file specifically. You add your config to the main configuration.yaml or sub config file.

The yaml files for switches, if toggled on will auto generate in the root of config_dir
